-- MySQL Script generated by MySQL Workbench
-- Fri Aug 31 10:26:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema forumdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forumdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forumdb` DEFAULT CHARACTER SET utf8 ;
USE `forumdb` ;

-- -----------------------------------------------------
-- Table `forumdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `suname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumdb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumdb`.`news` (
  `idNews` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idNews`, `idUser`),
  UNIQUE INDEX `idNews_UNIQUE` (`idNews` ASC),
  INDEX `fk_news_user_idx` (`idUser` ASC),
  CONSTRAINT `fk_news_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `forumdb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
